* research
** 2014-10-08
Present an original research topic that you would like to pursue in graduate school.
Describe the research idea, your general approach, as well as any unique resources that may be needed for accomplishing the research goal (i.e., access to national facilities or collections, collaborations, overseas work, etc.)
You may choose to include important literature citations.
Address the potential of the research to advance knowledge and understanding within science as well as the potential for broader impacts on society.
The research discussed must be in a field listed in the Solicitation (Section X, Fields of Study).
Page Limit - 2 pages

Type systems are out of control.
In graduate school, I hope to connect the alluring theoretical results of type theory to real-world software.
 
Why ``out of control''
- sexy types

Gradual typing in Hack + Swift.
Industry is leaving us behind.


Unclear benefits for now

Resources:
Matthias: tons of experience, untyped world, building things
Racket project as a proving ground
Nuprl connections pls
Amal: well typed lady, fully abstract compilation

Bottom line: stronger static guarantees.
The dream is provably correct systems (to replace the million-line unit test suites of today).
